### PR TITLE
guardians -> defense alliance

### PR DESCRIPTION
**Pull request by VasteelXolotl**
same term translated differently between question arcs and answer arcs. I'm for alliance instead of guardians, but guardians is accurate enough that it can work too as long as its kept consistent across games.

### CODE REVIEW

**Comment by orian34** [comment]
I don't think it should be changed since it's the term used everywhere?

**Comment by VasteelXolotl** [comment]
"Defense Alliance" is used to refer to the group in the Onikakushi and Himatsubushi translations while "Guardians" is used in the arcs from Meakashi onward. Could go the other way around where the instances of alliance would be changed to guardians. Either works, it's a matter of having it be consistent across all the arcs.
in hindsight it probably would've been smarter to make a poll on the preferred variant instead of diving into the editing

**Comment by 0xC0FFEE-Mug** [comment]
I'm a random nobody reading the story for the first time, but I did a double-take when I initially read "Guardians". I wasn't 100% sure if it was the same thing or some new group being introduced in this episode (as it had been called "Onigafuchi Defense Alliance" before) until the context afterwards clarified it.

**Comment by enumag** [comment]
I checked with the team on Discord. We decided to change it to Guardians so I'll close this and update the question arcs instead.

**Pull request closed without merging**
